version: '3.8'

services:
    mysql:
        image: mysql:5.7
        container_name: laravel-taskiteasy-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: taskiteasy
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpassword
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-taskiteasy-laravel
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-taskiteasy-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - mysql

volumes:
    mysql-data:
